name: Unit Test
on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]
  workflow_dispatch:
jobs:
  test:
    name : Release APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # JDK 설치
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      # APK 빌드
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace

      # APK 업로드
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug
