name: Unit Test
on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]
  workflow_dispatch:
jobs:
  test:
    name : Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # JDK 설치
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      # 유닛 테스트 실행
      - name: Unit tests
        run: bash ./gradlew test --stacktrace